spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_cache
    username: root
    password: aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名匹配规则